import path from "node:path"
import { NOT_HOLDING } from "./check"
import { Entry, LETTERS, Ledger, fieldRefs, formatRef, labelKey, status } from "./parse"

const GENERATED_NOTE =
  "<!-- Generated by `centina-check ledger` from this directory's ledger files. Do not edit. -->"

const OPEN_STATUSES = new Set(["open", "hypothesis", "predicted", "planned", "active", "blocked", "provisional"])
const OPEN_WORK = new Set(["planned", "active", "blocked"])
const RESOLVED = new Set(["done", "answered", "ratified", "chosen", "measured"])

function compareEntries(a: Entry, b: Entry): number {
  return (
    a.ref.scope.localeCompare(b.ref.scope) ||
    LETTERS.indexOf(a.ref.letter) - LETTERS.indexOf(b.ref.letter) ||
    a.ref.number - b.ref.number
  )
}

function sorted(entries: Entry[]): Entry[] {
  return [...entries].sort(compareEntries)
}

/** First definition of each label; duplicates are a check error, not an index concern. */
function uniqueEntries(ledger: Ledger): Entry[] {
  const byKey = new Map<string, Entry>()
  for (const entry of ledger.entries) if (!byKey.has(entry.key)) byKey.set(entry.key, entry)
  return sorted([...byKey.values()])
}

function cell(text: string): string {
  return text.replace(/\|/g, "\\|")
}

function table(header: string[], rows: string[][]): string[] {
  if (rows.length === 0) return ["_None._"]
  return [
    `| ${header.join(" | ")} |`,
    `| ${header.map(() => "---").join(" | ")} |`,
    ...rows.map((row) => `| ${row.map(cell).join(" | ")} |`),
  ]
}

function standingLines(entries: Entry[]): string[] {
  const goals = entries.filter((e) => e.ref.letter === "G" && status(e) === "active")
  const rules = entries.filter((e) => e.ref.letter === "R" && status(e) !== undefined && !NOT_HOLDING.has(status(e)!))
  const kindOf = (rule: Entry) => rule.fields.get("Kind")?.value

  // `limit` rules hold only because something is not built. They are listed
  // apart so the rule list stays a list of decisions meant to last.
  const decided = rules.filter((r) => kindOf(r) !== "limit")
  const limits = rules.filter((r) => kindOf(r) === "limit")

  const line = (rule: Entry, withKind: boolean) => {
    const notes = [withKind ? kindOf(rule) : undefined, status(rule) === "provisional" ? "provisional" : undefined]
    const present = notes.filter(Boolean)
    const note = present.length > 0 ? ` (${present.join(", ")})` : ""
    return `- \`${rule.key}\`${note}: ${rule.title}`
  }

  const section = (heading: string, lines: string[]) => [heading, "", ...(lines.length > 0 ? lines : ["_None._"])]

  return [
    ...section("## Goals", goals.map((g) => `- \`${g.key}\`: ${g.title}`)),
    "",
    ...section("## Rules", decided.map((r) => line(r, true))),
    "",
    ...section("## Current limits", limits.map((r) => line(r, false))),
  ]
}

export function renderStanding(ledger: Ledger): string {
  return [GENERATED_NOTE, "", `# Standing goals and rules: ${ledger.system}`, "", ...standingLines(uniqueEntries(ledger)), ""].join("\n")
}

/** Every label, for taking the next number in a scope and for looking up a label's file. */
export function renderLabels(ledger: Ledger): string {
  const entries = uniqueEntries(ledger)
  const relative = (file: string) => path.relative(ledger.dir, file)
  return [
    GENERATED_NOTE,
    "",
    `# All labels: ${ledger.system}`,
    "",
    ...table(
      ["Label", "Status", "Title", "File"],
      entries.map((e) => [e.key, status(e) ?? "", e.title, relative(e.file)]),
    ),
    "",
  ].join("\n")
}

export function affectedWorkItems(ledger: Ledger): { entry: Entry; reasons: string[] }[] {
  const entries = uniqueEntries(ledger)
  const byKey = new Map(entries.map((e) => [e.key, e]))
  const affected: { entry: Entry; reasons: string[] }[] = []

  for (const work of entries) {
    const workStatus = status(work)
    if (work.ref.letter !== "W" || !workStatus || !OPEN_WORK.has(workStatus)) continue
    const reasons: string[] = []
    for (const field of ["Depends-on", "Premises"]) {
      for (const ref of fieldRefs(work, field).refs) {
        const target = byKey.get(labelKey(ref))
        const targetStatus = target && status(target)
        if (!targetStatus) continue
        if (NOT_HOLDING.has(targetStatus)) reasons.push(`${field} ${formatRef(ref)} is ${targetStatus}`)
      }
    }

    // "May unblock" only holds when every Depends-on is resolved — one still
    // open means the item stays blocked regardless of the others, and saying
    // "may unblock" anyway sends the reader looking for an unblock that
    // cannot happen.
    if (workStatus === "blocked") {
      const resolved: string[] = []
      const open: string[] = []
      for (const ref of fieldRefs(work, "Depends-on").refs) {
        const target = byKey.get(labelKey(ref))
        const targetStatus = target && status(target)
        if (!targetStatus) continue
        if (RESOLVED.has(targetStatus)) resolved.push(`${formatRef(ref)} is ${targetStatus}`)
        else if (!NOT_HOLDING.has(targetStatus)) open.push(formatRef(ref))
      }
      if (resolved.length > 0) {
        reasons.push(
          open.length === 0
            ? `Depends-on ${resolved.join(", ")}; may unblock`
            : `Depends-on ${resolved.join(", ")}; still blocked on ${open.join(", ")}`,
        )
      }
    }

    if (reasons.length > 0) affected.push({ entry: work, reasons })
  }
  return affected
}

export function renderIndex(ledger: Ledger): string {
  const entries = uniqueEntries(ledger)

  const open = entries.filter((e) => OPEN_STATUSES.has(status(e) ?? ""))
  const phaseGroups = new Map<string, Entry[]>()
  for (const entry of open) {
    const phase = fieldRefs(entry, "Phase").refs[0]
    const group = phase ? `Phase ${formatRef(phase)}` : "No phase"
    phaseGroups.set(group, [...(phaseGroups.get(group) ?? []), entry])
  }
  const groupNames = [...phaseGroups.keys()].sort((a, b) =>
    a === "No phase" ? 1 : b === "No phase" ? -1 : a.localeCompare(b),
  )

  const lines = [
    GENERATED_NOTE,
    "",
    `# Ledger index: ${ledger.system}`,
    "",
    "# Standing",
    "",
    ...standingLines(entries),
    "",
    "# Affected work items",
    "",
  ]

  const affected = affectedWorkItems(ledger)
  if (affected.length === 0) lines.push("_None._")
  for (const { entry, reasons } of affected) {
    lines.push(`- \`${entry.key}\` (${status(entry)}): ${entry.title}`)
    for (const reason of reasons) lines.push(`  - ${reason}`)
  }

  lines.push("", "# Open items", "")
  if (groupNames.length === 0) lines.push("_None._")
  for (const group of groupNames) {
    lines.push(
      `## ${group}`,
      "",
      ...table(
        ["Label", "Kind", "Status", "Title"],
        phaseGroups.get(group)!.map((e) => [e.key, e.fields.get("Kind")?.value ?? "", status(e) ?? "", e.title]),
      ),
      "",
    )
  }

  const deferred = entries.filter((e) => status(e) === "deferred")
  lines.push(
    "# Deferred",
    "",
    ...table(["Label", "Title"], deferred.map((e) => [e.key, e.title])),
    "",
    "# Settled",
    "",
    ...table(
      ["Label", "Status", "Title", "Successor or evidence"],
      entries
        .filter((e) => NOT_HOLDING.has(status(e) ?? ""))
        .map((e) => [
          e.key,
          status(e)!,
          e.title,
          e.fields.get("Obsoleted-by")?.value ?? e.fields.get("Evidence")?.value ?? "",
        ]),
    ),
    "",
    "# All labels",
    "",
    "See `LEDGER-LABELS.md`.",
    "",
  )

  return lines.join("\n")
}
